services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iyzads
      POSTGRES_DB: iyzads
    networks:
      - iyzads
  test-db:
    image: postgres:17
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iyzads
      POSTGRES_DB: iyzads
    networks:
      - iyzads
networks:
  iyzads: